### ISSUE TITLE
When location services disabled then popup open but it dismiss automatically

### ISSUE THREAD

**Issue by jasmit34** [RajanMaheshwari/LocationManager#4]
![LocationPopup](https://user-images.githubusercontent.com/61501065/88171777-8bdfe900-cc3d-11ea-9dbb-c57333152506.png)

When location services disabled then popup open but it dismiss automatically, can we keep for user interaction?

**Comment by RajanMaheshwari** [comment]
Hi @jasmit34 
Actually, this is a system generated popup which dismiss automatically because I show our error received alert in the call back handler. If you comment out the code in closure error block i.e
```
if error != nil {
                self.alertMessage(message: (error?.localizedDescription)!, buttonText: "OK", completionHandler: nil)
                return
}
```
Then your system generated pop up will not dismiss as our alert dismiss that system generated pop up.

Also, this is the case when the user haven't chosen yet to allow or disallow the location services. If he chooses any of the action, then only our custom alert will be shown.

Another solution can be using
```
if LocationManager.shared.isLocationEnabled() {
             LocationManager.shared.getLocation { (location:CLLocation?, error:NSError?) in
        }
} else {
//show your alert
}
```
before making a call to get our current location.

**Comment by RajanMaheshwari** [comment]
Closing this issue as provided multiple alternative solutions.
